import type { Photo, Project, StudioProfile } from '../types';

export const DEFAULT_STUDIO: StudioProfile = {
  studioName: 'Budi Visual Story',
  whatsapp: '6281234567890',
  logoUrl: '',
  accentColor: '#1D1D1F',
  waTemplate: `Halo kak {client_name}! Pilihan foto kamu sudah masuk di Tandain.
Total: {total_selected} dari {quota} foto.
Status: Siap diproses untuk tahap editing RAW! ✨`,
  supabaseUrl: 'https://iwkxcppbhxdkiuborexk.supabase.co',
  supabaseAnonKey: 'sb_publishable_gIFstRxDA5Et-svM70T9Tg_jAAtNp95',
};

export const SAMPLE_GRADUATION_PHOTOS: Photo[] = [
  {
    id: 'wisuda-01',
    name: 'RANI_WISUDA_001.JPG',
    url: 'https://raw.githubusercontent.com/jimmyyrp/wisudara/main/public/portfolio-1.jpg',
    aspectRatio: 0.67,
  },
  {
    id: 'wisuda-02',
    name: 'RANI_WISUDA_002.JPG',
    url: 'https://raw.githubusercontent.com/jimmyyrp/wisudara/main/public/portfolio-2.jpg',
    aspectRatio: 0.8,
  },
  {
    id: 'wisuda-03',
    name: 'RANI_WISUDA_003.JPG',
    url: 'https://raw.githubusercontent.com/jimmyyrp/wisudara/main/public/portfolio-5.jpg',
    aspectRatio: 0.67,
  },
  {
    id: 'wisuda-04',
    name: 'RANI_WISUDA_004.JPG',
    url: 'https://raw.githubusercontent.com/jimmyyrp/wisudara/main/public/hero-image.jpg',
    aspectRatio: 1.5,
  },
  {
    id: 'wisuda-05',
    name: 'RANI_WISUDA_005.JPG',
    url: 'https://raw.githubusercontent.com/jimmyyrp/wisudara/main/public/about-image.jpg',
    aspectRatio: 1.33,
  },
  {
    id: 'wisuda-06',
    name: 'RANI_WISUDA_006.JPG',
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Foto_Wisuda.jpg',
    aspectRatio: 0.75,
  },
  {
    id: 'wisuda-07',
    name: 'RANI_WISUDA_007.JPG',
    url: 'https://upload.wikimedia.org/wikipedia/commons/9/92/Wisuda_UNJAYA.jpg',
    aspectRatio: 1.5,
  },
  {
    id: 'wisuda-08',
    name: 'RANI_WISUDA_008.JPG',
    url: 'https://raw.githubusercontent.com/jimmyyrp/wisudara/main/public/portfolio-4.jpg',
    aspectRatio: 0.8,
  },
  {
    id: 'wisuda-09',
    name: 'RANI_WISUDA_009.JPG',
    url: 'https://raw.githubusercontent.com/jimmyyrp/wisudara/main/public/portfolio-6.jpg',
    aspectRatio: 1.33,
  },
];

export const SAMPLE_WEDDING_PHOTOS: Photo[] = [
  {
    id: 'wed-01',
    name: 'IMG_4820.JPG',
    url: 'https://raw.githubusercontent.com/andikaputradev/wedding-invitation-nextjs/main/public/photos/cover1.jpg',
    aspectRatio: 0.67,
  },
  {
    id: 'wed-02',
    name: 'IMG_4821.JPG',
    url: 'https://raw.githubusercontent.com/andikaputradev/wedding-invitation-nextjs/main/public/photos/galeri-1.jpg',
    aspectRatio: 0.67,
  },
  {
    id: 'wed-03',
    name: 'IMG_4822.JPG',
    url: 'https://raw.githubusercontent.com/andikaputradev/wedding-invitation-nextjs/main/public/photos/galeri-2.jpg',
    aspectRatio: 0.67,
  },
  {
    id: 'wed-04',
    name: 'IMG_4823.JPG',
    url: 'https://raw.githubusercontent.com/andikaputradev/wedding-invitation-nextjs/main/public/photos/galeri-3.jpg',
    aspectRatio: 0.67,
  },
  {
    id: 'wed-05',
    name: 'IMG_4824.JPG',
    url: 'https://raw.githubusercontent.com/andikaputradev/wedding-invitation-nextjs/main/public/photos/galeri-4.jpg',
    aspectRatio: 0.67,
  },
  {
    id: 'wed-06',
    name: 'IMG_4825.JPG',
    url: 'https://raw.githubusercontent.com/andikaputradev/wedding-invitation-nextjs/main/public/photos/galeri-5.jpg',
    aspectRatio: 0.67,
  },
  {
    id: 'wed-07',
    name: 'IMG_4826.JPG',
    url: 'https://raw.githubusercontent.com/andikaputradev/wedding-invitation-nextjs/main/public/photos/galeri-6.jpg',
    aspectRatio: 0.67,
  },
  {
    id: 'wed-08',
    name: 'IMG_4827.JPG',
    url: 'https://raw.githubusercontent.com/winanda150/pawiwahan-theme-1/main/Elemen/Photo%20Gallery/Foto1.webp',
    aspectRatio: 1.5,
  },
  {
    id: 'wed-09',
    name: 'IMG_4828.JPG',
    url: 'https://raw.githubusercontent.com/winanda150/pawiwahan-theme-1/main/Elemen/Photo%20Gallery/Foto2.webp',
    aspectRatio: 1.33,
  },
  {
    id: 'wed-10',
    name: 'IMG_4829.JPG',
    url: 'https://raw.githubusercontent.com/winanda150/pawiwahan-theme-1/main/Elemen/Photo%20Gallery/Foto3.webp',
    aspectRatio: 0.75,
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-rani-wisuda',
    slug: 'rani-wisuda',
    clientName: 'Rani — Wisuda UI',
    sessionDate: '2026-10-04',
    driveFolderUrl: 'https://drive.google.com/drive/folders/1RaniWisudaSampleFolder2026',
    driveFolderId: '1RaniWisudaSampleFolder2026',
    quota: 5,
    pin: '',
    hasWatermark: false,
    status: 'lagi_milih',
    locked: false,
    activeSelectorDeviceId: 'dev-rani-hp',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    lastOpenedAt: new Date(Date.now() - 60000 * 12).toISOString(),
    expiresAt: new Date(Date.now() + 86400000 * 30).toISOString(),
    photos: SAMPLE_GRADUATION_PHOTOS,
    selectedFileNames: ['RANI_WISUDA_002.JPG', 'RANI_WISUDA_005.JPG'],
    revisionRound: 1,
    submissionHistory: [],
  },
  {
    id: 'proj-andi-rina',
    slug: 'andi-rina-wedding',
    clientName: 'Andi & Rina — Prewedding Day',
    sessionDate: '2026-09-28',
    driveFolderUrl: 'https://drive.google.com/drive/folders/1AndiRinaWeddingPlataran2026',
    driveFolderId: '1AndiRinaWeddingPlataran2026',
    quota: 6,
    pin: '2026',
    hasWatermark: true,
    status: 'udah_kirim',
    locked: true,
    activeSelectorDeviceId: 'dev-rina-iphone',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    lastOpenedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    submittedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    expiresAt: new Date(Date.now() + 86400000 * 27).toISOString(),
    photos: SAMPLE_WEDDING_PHOTOS,
    selectedFileNames: [
      'IMG_4820.JPG',
      'IMG_4821.JPG',
      'IMG_4823.JPG',
      'IMG_4825.JPG',
      'IMG_4826.JPG',
      'IMG_4829.JPG',
    ],
    revisionRound: 1,
    submissionHistory: [
      {
        round: 1,
        fileNames: [
          'IMG_4820.JPG',
          'IMG_4821.JPG',
          'IMG_4823.JPG',
          'IMG_4825.JPG',
          'IMG_4826.JPG',
          'IMG_4829.JPG',
        ],
        submittedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
      },
    ],
  },
  {
    id: 'proj-dimas-ayu',
    slug: 'dimas-ayu-prewed',
    clientName: 'Dimas & Ayu — Prewedding Bromo',
    sessionDate: '2026-09-20',
    driveFolderUrl: 'https://drive.google.com/drive/folders/1DimasAyuPreweddingSample',
    driveFolderId: '1DimasAyuPreweddingSample',
    quota: 8,
    hasWatermark: false,
    status: 'selesai',
    locked: true,
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    submittedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    expiresAt: new Date(Date.now() + 86400000 * 16).toISOString(),
    photos: SAMPLE_WEDDING_PHOTOS.slice(0, 10),
    selectedFileNames: ['IMG_4821.JPG', 'IMG_4824.JPG', 'IMG_4826.JPG', 'IMG_4827.JPG'],
    revisionRound: 1,
    submissionHistory: [],
  }
];
